#spring.application.name=vuelos_actuator
server.port=8002
server.servlet.context-path=/vuelos
spring.cloud.config.import-check.enabled=false
spring.profiles.active=dev

management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/metrics
