server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:reservasdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

vuelos:
  service:
    url: http://localhost:8081
    username: root
    password: root

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
