server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:vuelosdb
    driver-class-name: org.h2.Driver
    username: 
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  security:
    user:
      name: root
      password: root
      roles: root

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
